config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get 'home/about', to: 'homes#about'

  resources :musics, only: [:create, :index, :show, :edit, :update, :destroy, :new] do
  	resource :favorites, only: [:create, :destroy]
  	resources :music_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
    belongs_to :music
    validates_uniqueness_of :music_id, scope: :user_id
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :musics
	validates :category, presence: true
	def self.search(search)
      if search
        where(['category LIKE ?', "%#{search}%"])
      else
        all
      end
    end

end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
	include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/location.rb
class Location < ApplicationRecord
	has_many :musics
	validates :seen, presence: true
end

app/models/music.rb
class Music < ApplicationRecord
	belongs_to :user, optional: true
	belongs_to :genre
	belongs_to :location
	has_many :music_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	attachment :post_image
	validates :title, presence: true
	#validates :body, presence: true, length: { maximum:200}
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
	def self.search(search)
      if search
        where(['category LIKE ?', "%#{search}%"])
      else
        all
      end
    end
end

app/models/music_comment.rb
class MusicComment < ApplicationRecord
	belongs_to :user
	belongs_to :music
	validates :comment, presence: true
end

app/models/post_relation.rb
class PostRelation < ApplicationRecord
	belongs_to :music
	belongs_to :genre
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :following, class_name: "User"
    belongs_to :follower, class_name: "User"
    #validates :follower_id, presence: true
    #validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :musics, dependent: :destroy#アソシエーション 。Bookersの復習
  has_many :music_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  #validates :introduction, presence: true, length: { maximum:200}
  attachment :profile_image

  # ====================自分がフォローしているユーザーとの関連 ===================================
  #フォローする側のUserから見て、フォローされる側のUserを(中間テーブルを介して)集める。なので親はfollowing_id(フォローする側)
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  # 中間テーブルを介して「follower」モデルのUser(フォローされた側)を集めることを「followings」と定義
  has_many :followings, through: :active_relationships, source: :follower
  # ========================================================================================

  # ====================自分がフォローされるユーザーとの関連 ===================================
  #フォローされる側のUserから見て、フォローしてくる側のUserを(中間テーブルを介して)集める。なので親はfollower_id(フォローされる側)
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  # 中間テーブルを介して「following」モデルのUser(フォローする側)を集めることを「followers」と定義
  has_many :followers, through: :passive_relationships, source: :following
  # =======================================================================================
  def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relationships.find_by(following_id: user.id).present?
  end
  validates :name, presence: true,  length: { minimum: 2, maximum: 20}#名前は2文字以上20文字以内。それ以外はエラーを表示。
  validates :introduction, length: { maximum: 50}#感想が50文字を超える場合はエラーを表示
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController


def genre_params
	params.require(:genre).permit(:category)
end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
	before_action :authenticate_user!

  def new
  	@music = Music.new
  end

  def index
  	@user = current_user
  	@musics = Music.all
    @musics = Music.page(params[:page]).reverse_order
    @musics = Kaminari.paginate_array(@musics).page(params[:page]).per(5)
  	@music = Music.new
    @genres = Genre.all
    @locations = Location.all
    @q = current_user.musics.ransack(params[:q])
    @musics = @q.result(distinct: true)
  end

  def show
  	@music = Music.find(params[:id])
  	@user = @music.user
  	@new_music = Music.new
  	@music_comment = MusicComment.new
  	@music_comments = @music.music_comments
  end


  def edit
  	@music = Music.find(params[:id])
  	if @music.user_id != current_user.id
  		redirect_to musics_path
  end
  end

  def create
    #binding.pry
  	@music = Music.new(music_params)
  	@music.user_id = current_user.id
  	if @music.save
  		flash[:notice] = "successfully"
  		redirect_to musics_path
  	else
  		@musics = Music.all
  		@user = current_user
  		flash[:error] = "error"
  		render :new
  	end
    end

    def update
    @music = Music.find(params[:id])
    @music.user_id = current_user.id
    if @music.update(music_params)
    	flash[:notice] = "successfully"
    	redirect_to music_path(@music.id)
    else
    	flash[:notice] = "error"
    	render :edit
    end
end

    def destroy
    	@music = Music.find(params[:id])
    	@music.destroy
    	redirect_to musics_path
    end

    def search
      @musics = Music.search(params[:search])
    end

    private
    def music_params
    	params.require(:music).permit(:title,:post_image, :genre_id, :category, :artist, :music_comment,:impression,:name,:seen,:location_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

  def index
  	@user = current_user
  	@music = Music.new
    @users = User.all
  end

  def show
  	@music = Music.new
  	@user = User.find(params[:id])
  	@musics = @user.musics
  end

  def edit
  	@user = User.find(params[:id])
  	if @user != current_user
  		redirect_to user_path(current_user.id)
  end
end
  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		flash[:nitice] = "success"
  		redirect_to users_path(@user.id)
  	else
  		flash[:notice] = "error"
  		render :edit
  	end
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end
  private
  def user_params
  	params.require(:user).permit(:name, :profile_image,:introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/musics/edit.html.erb
<div class="editbody">
<h1>投稿編集</h1>

<%= form_for(@music) do |f| %>

<% if @music.errors.any? %>
  <h2><%= @music.errors.count %>error prohibited this obj from being saved:</h2>
  <ul><% @music.errors.full_messages.each do |messages| %></ul>
    <li><%= messages %></li>
  <% end %>
<% end %>
<div class="field">
<%= attachment_image_tag @music, :post_image,  fallback: "no_image.jpg", size: "60x60" %>
  <h4>アーティスト</h4>
  <div class="field">
    <%= f.text_field :artist, :size => "50*50" %>
  <h4>タイトル</h4>
  <div class="field">
    <%= f.text_field :title, :size => "50*50" %>
  </div>
  <div class="field">
    <h4>おすすめポイント</h4>
    <%= f.text_field :impression, :size => "50*50" %>
  <div class="field">
    <h4>ジャンル</h4>
      <%= f.collection_select :genre_id, Genre.all,:id,:category %>
    <h4>おすすめシーン</h4><%= f.collection_select :location_id, Location.all,:id,:seen %>
  </div>

  <div class="actions row">
   <%= f.submit '編集完了',class: "btn btn-primary"%>
  </div>
  <% end %>
  <div class="actions row">

<%= link_to "詳細", music_path,　class: "btn btn-primary" %>
<%= link_to "戻る", musics_path,　class: "btn btn-primary" %>
</div>
</div>
</div>

app/views/musics/index.html.erb
<div class="indexbody">
<div class="container">
  <div class="row">
    <% if @music.errors.any? %>
      <%= @music.errors.count %>件のerrorが発生しました
      <% @music.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
   </div>
  <div class="col-xs-3">
    </div>
      <h2><i class="fas fa-search"></i>キーワード検索</h2>
      <%= search_form_for @q do |f| %>
        <%= f.label :genre, "ジャンル" %>
        <%= f.collection_select :genre_id, Genre.all,:id,:category %>
        <%#= f.search_field :genre_category_cont %>
        <%= f.submit "検索" %>
        <%= f.label :location, "おすすめシーン" %>
        
        <%= f.collection_select :location_id, Location.all,:id,:seen %><%#= f.search_field :location_seen_cont %>
        <%= f.submit "検索" %>
      <%= link_to "+新規投稿", new_music_path, class: "btn btn-primary btn-circle pull-right" %>
      <h1>投稿一覧</h1>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>投稿者<i class="fas fa-user-alt"></i></th>
            <th>画像<i class="fas fa-camera-retro"></i></th>
            <th>アーティスト<i class="fas fa-microphone"></i></th>
            <th></th>
            <th>タイトル<i class="fas fa-music"></i></th>
            <th></th>
            <th>ジャンル<i class="fas fa-star"></i></th>
            <th>おすすめシーン<i class="fas fa-tree"></i></th>
            <th>一言<i class="fas fa-comment"></i></th>
            <th>イイね<i class="fas fa-heart"></i></th>
            <th>コメント<i class="fas fa-comments"></i></i></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @musics.each do |music| %>
          <div class="member">
          <tr>
            <td><%= @user.name %></td>
            <td><%= attachment_image_tag music, :post_image, format: 'jpg' ,size: "100x100", fallback: "no_image.jpg" %></td>
          <td><%= music.artist %></td>
          <%= link_to music_path(music.id) do %>
              <td>
                <% end %>
              </td>
              <td>
                <%= link_to music.title, music_path(music.id) %>
              </td>
              <td></td>
              <td><%= music.genre.category %></td>
              <td><%= music.location.seen %></td>
              <td><%= music.impression %></td>
            </div>
              <!--以下いいね機能の実装-->
              <% if music.favorited_by?(current_user) %>
              <td><%= link_to music_favorites_path(music), method: :delete do %></td>
              <td><%= render 'favorites/favorite_button', music: music %></td>
              <% end %>
            <% else %>
            <td><%= link_to music_favorites_path(music), method: :post do %>
                <i class="fa fa-heart-o" aria-hidden="true"></i>
                <%= music.favorites.count %>
                <% end %>
            </td>
            <% end %>

            <td><%= link_to "#{music.music_comments.count} コメント", music_path(music.id) %></td>
            </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
</div>

app/views/musics/new.html.erb
<div class="newbody">
<div class="body-height">
<div class="container">
  <h1>新規投稿</h1>
    <%= form_for @music, :url => {controller:  :musics, action: :create} do |f| %>
    <div class="form-group">
  <%= f.attachment_field :post_image %>
    </div>
      <h3>アーティスト</h3>
    <div class="field">
        <%= f.text_field :artist %>
    </div>
      <h3>タイトル</h3>
      <div class="field">
        <%= f.text_field :title %>
    </div>
      <div class="field">
      <h3>一言</h3>
      <div class="field">
        <%= f.text_area :impression %>
    </div>
      <h3>ジャンル</h3>
      <div class="field">
        <%= f.collection_select :genre_id, Genre.all,:id,:category %>
      </div>
      <h3>おすすめのシーン</h3>
      <div class="field">
      <%= f.collection_select :location_id, Location.all,:id,:seen %>
    </div>

      <%= f.submit '新規登録', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</div>
</div>

app/views/musics/show.html.erb
<div class="showbody">
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<h2>Music detail</h2>
<%= @user.name %>
    <%= attachment_image_tag @user, :profile_image,  fallback: "no_image.jpg", size: "60x60" %>
	<table class="table table-striped">
		 <tbody>
			<tr>
        <th></th>
        <th>アーティスト<i class="fas fa-microphone"></th>
        <th>タイトル<i class="fas fa-music"></i></th>
        <th>ジャンル<i class="fas fa-star"></i></th>
        <th>おすすめシーン<i class="fas fa-tree"></i></th>
        <th>一言<i class="fas fa-comment"></i></th>
        <th colspan="3"></th>
      </tr>
			<tr>
          <td><%= link_to user_path(@user.id) do %></td>
          <td><%= @music.artist %></td>
					<td><%=  @music.title  %></td>
					<td><%= @music.genre.category %></td>
          <td><%= @music.location.seen %></td>
					<td><%= @music.impression %></td>
					<% if @music.user_id == current_user.id %>
					<td> <%= link_to "Edit", edit_music_path(@music.id) ,class:"btn-sm btn-success edit_music_10349" %></td>
					<td><%= link_to "Destroy", music_path(@music.id), method: :delete,  "data-confirm" => "本当に削除しますか？"  ,class:"btn-sm btn-danger destroy_book_10349"%></td>
				    <% end %>
				</tr>
				</tbody>
			</table>
			<!--以下コメント機能実装-->
			<%= form_for [@music, @music_comment] do |f| %>
<div class="row">
<div class="col-sm-12">
    <h3>コメント</h3>
      <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
</div>
</div>
      <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
      <%= render 'music_comments/comments', music: @music %>
      <% end %>
<% end %>
</div>
</div>
</div>
</div>
</div>

app/views/users/_sidebar.html.erb
<div class="showuser">
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
  <% end %>
<h2>ユーザー情報</h2>
<a><%= attachment_image_tag user, :profile_image, format: 'jpg' ,size: "100x100", fallback: "no_image.jpg" %></a>
<table class="table">
  <tbody>
    <tr>
        <th>名前</th>
        <th><%= @user.name %>さんのページ</th>
    </tr>
    <tr>
        <th>プロフィール</th>
        <th><%= @user.introduction %></th>
    </tr>
    <tr>
      <th>フォロー数</th>
      <th><%=link_to @user.followings.count, follows_user_path(@user.id) %></th>
    </tr>

    <tr>
      <th>フォロワー数</th>
      <th><%=link_to @user.followers.count, followers_user_path(@user.id) %></th>
    </tr>
    <tr>
      <th><%= link_to 'プロフィール編集', edit_user_path(@user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{@user.id}" %></th>
    </tr>
  </tbody>
</table>
</div>

app/views/users/edit.html.erb
<div class="useredit">
<div class="body-height">
<div class="field">
<h1>登録情報編集</h1>

   <%= form_for(@user) do |f| %>
   <% if @user.errors.any? %>
  <h2><%= @user.errors.count %>error prohibited this obj from being saved:</h2>
  <ul><% @user.errors.full_messages.each do |messages| %></ul>
    <li><%= messages %></li>
  <% end %>
  <% end %>
  <div class="field">
   <h3>名前</h3>
    <%= f.text_field :name%>
  </div>
  <div class="form-group">
   <h3>画像</h3>
    <%= f.attachment_field :profile_image  %>
  </div>

  <div class="field">
    <h3>自己紹介文</h3>
    <%= f.text_area :introduction %>
  </div>



  <div class="actions">
    <%= f.submit "登録情報更新" %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/users/followers.html.erb
<h1>Followers Users</h1>
<table class="table">
    <thead>
        <tr>
          <th>画像</th>
          <th>名前</th>
          <th colspan="3"></th>
        </tr>
    </thead>
  <tbody>
<% @users.each do |user| %>
        <tr>
            <td><a><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "60x60" %></a></td>
            <td><%= user.name %></td>
            <td><p>フォロー数：<%= user.followings.count %></p></td><!--フォロー数のカウント下記も同じ-->
            <td><p>フォロワー数：<%= user.followers.count %></p></td>
            <td><%= link_to "Show", user_path(user.id) %></td><!--show画面への遷移-->
<% end %>
  </tbody>
</table>

app/views/users/follows.html.erb
<h1>フォローユーザー</h1>
  <table class="table">
    <thead>
        <tr>
            <th>画像</th>
            <th>名前</th>
            <th colspan="3"></th>
        </tr>
    </thead>
      <tbody>
  <% @users.each do |user| %>
        <tr>
          <td><a><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "60x60" %></a></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user.id) %></td><!--show画面への遷移-->
        </tr>
  <% if current_user != user %>
  <% if user.followed_by?(current_user) %>
        <p><%=link_to "フォロー解除", user_relationships_path(user.id), method: :delete %></p>
        <% else %>
        <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
        <% end %>
        <% end %>
        <% end %>
      </tbody>
  </table>

app/views/users/index.html.erb
<div class="userindex">
<div class="container">
<div class="row">
<div class="col-xs-3">
      <%= render 'users/sidebar' ,user: @user,music:@music %>
</div>
<div class="col-xs-9">
          <h2>マイページ</h2>
          <%= link_to "+新規投稿", new_music_path, class: "btn btn-primary btn-circle pull-right" %>
    <table class="table table-striped">
      <thead>
          <tr>
              <th>画像<i class="fas fa-camera-retro"></i></th>
              <th>名前<i class="fas fa-user-alt"></i></th>
              <th>フォロー<i class="fas fa-user-friends"></i></th>
              <th>フォロワー<i class="fas fa-users"></i></th>
              <th colspan="3"></th>
          </tr>
      </thead>
      <tbody>
              <% @users.each do |user| %>
          <tr>
              <td><a><%= attachment_image_tag user, :profile_image, format: 'jpg' ,size: "100x100", fallback: "no_image.jpg" %></a></td>
                  <td><%= user.name %></td>
                  <td><p><%= user.followings.count %></p></td><!--フォロー数のカウント下記も同じ-->
                  <td><p><%= user.followers.count %></p></td>

              <% if current_user != user %>
                  <!--ログイン済みのユーザーである場合-->
              <% if user.followed_by?(current_user) %><!-- ログイン済みのユーザーがフォロー-->
                  <td><%=link_to "フォロー解除", user_relationships_path(user.id), method: :delete %></td>
              <% else %>
                  <td><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></td>
                  <td><%= link_to "詳細", user_path(user.id) %></td><!--show画面への遷移-->
          </tr>
              <% end %>
              <% end %>
              <% end %>
      </tbody>
    </table>
        </div>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
<div class="usershow">
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
  <% end %>
<div class="container">
<div class="row">
<div class="col-xs-3">
      <h2>ユーザー情報</h2>
  <table class="table">
    <tbody>
    <tr>
        <th>名前</th>
        <th><%= @user.name %>さんのページ</th>
        <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "100x100" %>
    </tr>
    <tr>
        <th>プロフィール</th>
        <th><%= @user.introduction %></th>
    </tr>
    <tr>
       <th>フォロー数</th>
       <th><%=link_to @user.followings.count, follows_user_path(@user.id) %><th>
    </tr>

    <tr>
        <th>フォロワー数</th>
        <th><%=link_to @user.followers.count, followers_user_path(@user.id) %></th>
    </tr>
    <tr>
        <th><%= link_to 'プロフィール編集', edit_user_path(@user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{@user.id}" %></th>
    </tr>

     <% if current_user != @user %>
                  <!--ログイン済みのユーザーである場合-->
     <% if @user.followed_by?(current_user) %>
     <td><%=link_to "フォロー解除", user_relationships_path(@user.id), method: :delete %></td>
              <% else %>
     <td><%=link_to "フォローする", user_relationships_path(@user.id), method: :post %></td>
     <% end %>
     <% end %>
    </tbody>
  </table>
</div>
<div class="col-xs-9">
      <h3>投稿履歴</h3>
      <%= link_to "+新規投稿", new_music_path, class: "btn btn-primary btn-circle pull-right" %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>画像<i class="fas fa-camera-retro"></i></th>
          <th>アーティスト<i class="fas fa-microphone"></i></th>
          <th>タイトル<i class="fas fa-music"></i></th>
          <th>ジャンル<i class="fas fa-star"></i></th>
          <th>おすすめシーン<i class="fas fa-tree"></i></th>
          <th>一言<i class="fas fa-comment"></i></th>
        </tr>
      </thead>
      <tbody>
        <% @musics.each do |music| %>
          <tr>
            <td><%= link_to  user_path(@user.id) do %>
                <%= attachment_image_tag music, :post_image, format: 'jpg' ,size: "100x100", fallback: "no_image.jpg" %>
            </td>
            <td><%= music.artist %></td>
            <td><%= link_to music.title, music_path(music) %></td>
            <td><%= music.genre.category %></td>
            <td><%= music.location.seen %></td>
            <td><%= music.impression %></td>
          </tr>
        <% end %>
        <% end %>
      </tbody>
      </table>
    </div>
  </div>
</div>
</div>