config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get 'home/about', to: 'homes#about'

  resources :musics, only: [:create, :index, :show, :edit, :update, :destroy, :new] do
  	resource :favorites, only: [:create, :destroy]
  	resources :music_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
    belongs_to :music
    validates_uniqueness_of :music_id, scope: :user_id
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :musics
	validates :category, presence: true
	def self.search(search)
      if search
        where(['category LIKE ?', "%#{search}%"])
      else
        all
      end
    end

end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
	include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/location.rb
class Location < ApplicationRecord
	has_many :musics
	validates :seen, presence: true
end

app/models/music.rb
class Music < ApplicationRecord
	belongs_to :user, optional: true
	belongs_to :genre
	belongs_to :location
	has_many :music_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	attachment :post_image
	validates :title, presence: true
	#validates :body, presence: true, length: { maximum:200}
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
	def self.search(search)
      if search
        where(['category LIKE ?', "%#{search}%"])
      else
        all
      end
    end
end

app/models/music_comment.rb
class MusicComment < ApplicationRecord
	belongs_to :user
	belongs_to :music
	validates :comment, presence: true
end

app/models/post_relation.rb
class PostRelation < ApplicationRecord
	belongs_to :music
	belongs_to :genre
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :following, class_name: "User"
    belongs_to :follower, class_name: "User"
    #validates :follower_id, presence: true
    #validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :musics, dependent: :destroy#アソシエーション 。Bookersの復習
  has_many :music_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  #validates :introduction, presence: true, length: { maximum:200}
  attachment :profile_image

  # ====================自分がフォローしているユーザーとの関連 ===================================
  #フォローする側のUserから見て、フォローされる側のUserを(中間テーブルを介して)集める。なので親はfollowing_id(フォローする側)
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  # 中間テーブルを介して「follower」モデルのUser(フォローされた側)を集めることを「followings」と定義
  has_many :followings, through: :active_relationships, source: :follower
  # ========================================================================================

  # ====================自分がフォローされるユーザーとの関連 ===================================
  #フォローされる側のUserから見て、フォローしてくる側のUserを(中間テーブルを介して)集める。なので親はfollower_id(フォローされる側)
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  # 中間テーブルを介して「following」モデルのUser(フォローする側)を集めることを「followers」と定義
  has_many :followers, through: :passive_relationships, source: :following
  # =======================================================================================
  def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relationships.find_by(following_id: user.id).present?
  end
  validates :name, presence: true,  length: { minimum: 2, maximum: 20}#名前は2文字以上20文字以内。それ以外はエラーを表示。
  validates :introduction, length: { maximum: 50}#感想が50文字を超える場合はエラーを表示
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

  def index
  	@user = current_user
  	@music = Music.new
    @users = User.all
  end

  def show
  	@music = Music.new
  	@user = User.find(params[:id])
  	@musics = @user.musics
  end

  def edit
  	@user = User.find(params[:id])
  	if @user != current_user
  		redirect_to user_path(current_user.id)
  end
end
  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		flash[:nitice] = "success"
  		redirect_to users_path(@user.id)
  	else
  		flash[:notice] = "error"
  		render :edit
  	end
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end
  private
  def user_params
  	params.require(:user).permit(:name, :profile_image,:introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WithMusic</title>
    <script src="https://kit.fontawesome.com/82d88901b5.js" crossorigin="anonymous"></script>
    <!-- <script
  src="https://code.jquery.com/jquery-.3.1.1min.js"
  integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
  crossorigin="anonymous"></script> -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
<header class="navbar navbar-inverse navbar-bottom">
  <div class="container">

<nav class="nav navbar-nav navbar-left">
    <nav class="text-muted"><span><strong><%= link_to "with music" , users_path %></strong></span></nav>
</nav>
<nav>
  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
    <li><%= link_to user_path(current_user.id) do %>
      <p><i class="fas fa-home"></i>Home</p>
      <% end %>
      </li>
      <li><%= link_to users_path  do %>
      <p><i class="fas fa-user"></i>マイページ</p>
      <% end %>
      </li>


      <li><%= link_to musics_path do %>
      <p><i class="fas fa-music"></i>投稿</p>
      <% end %>
      </li>

      <li><%= link_to destroy_user_session_path, method: :delete do %>
      <p><i class="fas fa-sign-out-alt"></i>ログアウト</p>
      <% end %>
      </li>

      <% else %>

      <li><%= link_to root_path do %>
      <p><i class="fas fa-home"></i>Home</p>
      <% end %>
      </li>

      <li><%= link_to home_about_path do %>
      <p><i class="fas fa-question-circle"></i>with musicとは？</p>
      <% end %>
      </li>

      <li><%= link_to new_user_registration_path do %>
      <p><i class="fas fa-user-plus"></i>新規登録</p>
      <% end %>
      </li>

      <li><%= link_to new_user_session_path do %>
      <p><i class="fas fa-sign-in-alt"></i>ログイン</p>
      <% end %>
    </li>
    <%# end %>
    <% end %>
  </ul>
</nav>
</div>
</div>
</header>
<%= yield %>
<div class="footer">
  <div class='container'>
      <div class='row'>
               <div class="nav navbar-nav navbar-right">
               <a href="https://www.apple.com/jp/apple-music/"><i class="fab fa-apple fa-3x"></i></a>
               <a href="https://www.youtube.com/"><i class="fab fa-youtube fa-3x"></i></a>
               <a href="https://www.amazon.co.jp/music/unlimited/ref=dmm_acq_marin_d_bra_zzz_5tXCd5hO-dc_c_423719225969/"><i class="fab fa-amazon fa-3x"></i></a>
               <a href="https://www.spotify.com/jp/"><i class="fab fa-spotify fa-3x"></i></a>
        </div>
        </div>
      </div>
    </div>
  </footer>
</body>
</html>